### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by chrisjm** [chrisjm/openbrewerydb-website#10]
**Is your feature request related to a problem? Please describe.**
The site is kinda ooogly.

**Describe the solution you'd like**
Pretty site with awesome stuff.

**Additional context**
I designed the first iteration. Mainly just wanted to get it out into the world 🤷‍♂️

**Comment by bmweeden** [comment]
@chrisjm is this something that you still want help with?

**Comment by chrisjm** [comment]
@bmweeden Yes, for sure! If you have design time to contribute that would be great! Let me know what you need from me or questions you have. Thank you!

**Comment by chrisjm** [comment]
Heya @bmweeden! Just a ping to see if you were still interested in doing the redesign. If not, no worries!

**Comment by chrisjm** [comment]
I'm hoping to migrate things to Gatsby soon (#8), but it will still require a little design love afterwards. 

Note that I'm planning to use the following starter template style:

![717df732cb277eb8d8e990a819ce3c28](https://user-images.githubusercontent.com/96110/67303742-b67ef480-f4a7-11e9-9eee-31a4e8fb69c8.png)

**Comment by chrisjm** [comment]
I created a new repo for this website here: https://github.com/chrisjm/openbrewerydb-gatsby

I'm closing this issue because it will be moved there once the website is released.

See issue #8 for more details.
